#
# * Config
# * Stores static configuration and project data (use spaces, not tabs)
# *
# * Copyright (c) 2014 SoftLayer, an IBM Company
# * Released under the MIT license
#

# ==============================
# Project
# ==============================

project:
  name:           Python Bindings
  tagline:        A set of Python libraries that assist in calling the SoftLayer API
  www:            http://softlayer.github.io/softlayer-python
  version:        0.3.0

# ==============================
# Company
# ==============================

company:
  name:           "SoftLayer, an IBM Company"  # quotes are required only if punctuation is present in the name
  www:            http://www.softlayer.com
  twitter:        SoftLayerDevs

# ==============================
# License
# ==============================

license:
  type:           MIT
  www:            http://github.com/softlayer/softlayer-python/blob/master/LICENSE

# ==============================
# GitHub
# ==============================

github:
  org:            http://github.com/softlayer
  repo:           http://github.com/softlayer/softlayer-python
  fork:           http://github.com/softlayer/softlayer-python/fork
  star:           http://github.com/softlayer/softlayer-python/stargazers
  commits:        http://github.com/softlayer/softlayer-python/commits
  contributors:   http://github.com/softlayer/softlayer-python/contributors
  issues:         http://github.com/softlayer/softlayer-python/issues?state=open
  milestones:     http://github.com/softlayer/softlayer-python/issues/milestones?state=open

# ==============================
# API (GitHub)
# ==============================

api:
  commits:        https://api.github.com/repos/softlayer/softlayer-python/commits?state=closed/callback?
  contributors:   https://api.github.com/repos/softlayer/softlayer-python/contributors?callback=?
  members:        https://api.github.com/orgs/softlayer/members?callback=?
  milestones:     https://api.github.com/repos/softlayer/softlayer-python/milestones?state=closed/callback?
  pulls:          https://api.github.com/repos/softlayer/softlayer-python/pulls?callback=?
  repos:          https://api.github.com/orgs/softlayer/repos?callback=?
  stargazers:     https://api.github.com/repos/softlayer/softlayer-python/stargazers?callback=?
  tags:           https://api.github.com/repos/softlayer/softlayer-python/tags?callback?
  watchers:       https://api.github.com/repos/softlayer/softlayer-python/subscribers?callback=?

# ==============================
# Markdown
# ==============================

highlighter:      rouge
markdown:         redcarpet
redcarpet:
  extensions:     [ "autolink",
                    "fenced_code_blocks",
                    "lax_spacing",
                    "smart",
                    "strikethrough",
                    "superscript",
                    "tables",
                    "underline",
                    "with_toc_data"
                  ]

# ==============================
# Server
# ==============================

baseurl:          /softlayer-python
permalink:        pretty
exclude:          [ ".gitignore",
                    "Gemfile",
                    "Gruntfile.coffee",
                    "coffeescript",
                    "less",
                    "node_modules",
                    "package.json",
                    "Rakefile"
                  ]

# ==============================
# Analytics
# ==============================

google:
  id:             UA-XXXXXXXX-X
  domain:         XXXXXX.github.io
